### ISSUE TITLE
DuerOS接入快速指南-App接入.pdf内SDK下载链接失效

### ISSUE THREAD

**Issue by welaunchcn** [dueros/AndroidBotSdkDemo#1]
4.4.1 集成 BotSDK
1) 下载 SDK 并放入到 app/libs 目录：下载链接
https://github.com/dueros/AndroidBotSdkDemo/blob/master/app/libs/botsdk-1.0.0.12.aar

**Comment by TokenChen** [comment]
现在已经改为maven依赖，依赖方式：

在项目build.gradle中新增 maven库依赖

maven{ url 'https://dueros.baidu.com/maven/repository/maven-releases/'}
在app/build.gradle加入依赖

implementation 'com.alibaba:fastjson:1.1.71.android'
implementation 'com.baidu.duer.botsdk:bot-sdk-android:1.35.0@aar'
