### ISSUE TITLE
如何提交APK文件

### ISSUE THREAD

**Issue by welaunchcn** [dueros/AndroidBotSdkDemo#2]
新建技能选择Android App模板只能填写APP包名，如何提交APP的APK文件？

**Comment by TokenChen** [comment]
请提交apk文件给到百度接口人，
2020.Q2 技能开放平台会升级，支持apk发版。

**Comment by TokenChen** [comment]
> 新建技能选择Android App模板只能填写APP包名，如何提交APP的APK文件？

技能创建完毕后，需要等待平台审核（一般1~2个工作日）
技能审核完毕，可以在技能[控制台](https://dueros.baidu.com/dbp/main/console)->点击进入技能信息页面->发布管理->发布上线页面上传apk。
