### ISSUE TITLE
adb连接设备提示未授权(adb devices unauthorized) 麻烦帮我推送下开发版

### ISSUE THREAD

**Issue by yourchanges** [dueros/AndroidBotSdkDemo#5]
麻烦帮我推送下开发版

设备信息如下：
```
设备序列号  3F19101FA18A7706
软件版本 5.27.0-5624.CM32
系统版本 5.25.0-2054.CM32
硬件版本 1.0.1

小度在家 NV5001
```

**Comment by yourchanges** [comment]
技能ID  5e517620-1554-d2a4-e307-e62359555ad6

**Comment by yourchanges** [comment]
和官方确认
"
目前开发版本升级只支持1S（NV6001）/1A(NV2001)/X8（8寸那一款，XDH-0F-A1）

暂不支持NV5001升级开发版本。因为NV5001这款设备，存储空间限制，不支持安装app。
"

**Comment by TokenChen** [comment]
进入开放平台[控制台](https://dueros.baidu.com/dbp/main/console) -> 进入技能信息页面 -> 测试验证 -> 真机测试 -> 页面内可以自助升级开发版本。
因为存储空间限制，4G存储空间的设备不支持开发/调试/安装 apk技能。需要用8G存储空间的小度设备开发调试，例如小度在家1S/1A/X8/X10 等等
